<<<<<<< HEAD
=======
version: '3.9'

>>>>>>> 75f83eecc9e9613579c37fd632041528d553a53d
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
<<<<<<< HEAD

  longan-map:
    build:
      context: ./longan-map
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
=======
>>>>>>> 75f83eecc9e9613579c37fd632041528d553a53d
